apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: schemas.mysql.sample.javaoperatorsdk
spec:
  group: mysql.sample.javaoperatorsdk
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - encoding
              properties:
                encoding:
                  type: string
  scope: Namespaced
  names:
    plural: schemas
    singular: schema
    kind: MySQLSchema
