apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: schemas.mysql.sample.javaoperatorsdk.io
spec:
  group: mysql.sample.javaoperatorsdk.io
  version: v1
  subresources:
    status: {}
  scope: Namespaced
  names:
    plural: schemas
    singular: schema
    kind: MySQLSchema
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          required:
          - encoding
          properties:
            encoding:
              type: string
