apiVersion: v1
kind: Namespace
metadata:
  name: minio-operator-ns
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: minioinstances.operator.min.io
spec:
  group: operator.min.io
  scope: Namespaced
  names:
    kind: MinIOInstance
    singular: minioinstance
    plural: minioinstances
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                replicas:
                  type: integer
                  minimum: 1
                  maximum: 32
                version:
                  type: string
                mountpath:
                  type: string
                subpath:
                  type: string
      additionalPrinterColumns:
        - name: Replicas
          type: integer
          jsonPath: ".spec.replicas"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-operator-sa
  namespace: minio-operator-ns
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: minio-operator-binding
  namespace: minio-operator-ns
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: minio-operator-sa
  namespace: minio-operator-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-operator
  namespace: minio-operator-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      name: minio-operator
  template:
    metadata:
      labels:
        name: minio-operator
    spec:
      serviceAccountName: minio-operator-sa
      containers:
        - name: minio-operator
          image: minio/k8s-operator:2.0.0
          imagePullPolicy: IfNotPresent