apiVersion: operator.min.io/v1
kind: MinIOInstance
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  metadata:
    labels:
      app: minio
  image: minio/minio:RELEASE.2020-05-01T22-19-14Z
  serviceName: minio
  volumesPerServer: 1
  mountPath: /export
  volumeClaimTemplate:
    metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  credsSecret:
    name: minio-creds-secret
  podManagementPolicy: Parallel
  requestAutoCert: false
  certConfig:
    commonName: ""
    organizationName: []
    dnsNames: []
  env:
    - name: MINIO_BROWSER
      value: "on"
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
  liveness:
    httpGet:
      path: /minio/health/live
      port: 9000
    initialDelaySeconds: 120
    periodSeconds: 60
  readiness:
    httpGet:
      path: /minio/health/ready
      port: 9000
    initialDelaySeconds: 120
    periodSeconds: 60