apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: ClusterIP
  ports:
    - name: http-minio
      port: 9000
      targetPort: 9000
      protocol: HTTP
  selector:
    app: minio