name: Verify Pull Request
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 15]
        kubernetes: ['v1.17.13','v1.18.12','v1.19.4']
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }} # to avoid cloning in detached state (which would break committing)
#      - name: Format code
#        uses: axel-op/googlejavaformat-action@v3
#        with:
#          commitMessage: "chore(format): re-format code"
#          args: "--replace"
      - name: Check commit format
        uses: talos-systems/conform@v0.1.0-alpha.20
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Run unit tests
        run: mvn -B test --file pom.xml
      - name: Set up Minikube
        uses: manusa/actions-setup-minikube@v2.3.0
        with:
          minikube version: 'v1.15.1'
          kubernetes version: ${{ matrix.kubernetes }}
          driver: 'docker'
      - name: Run integration tests
        run: mvn -B package -P no-unit-tests --file pom.xml

